# Generated by Django 5.2.5 on 2025-09-01 16:11

import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Custom meta title for SEO (max 70 characters). Leave blank to use the default title.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Custom meta description for SEO (max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "focus_keyword",
                    models.CharField(
                        blank=True,
                        help_text="Main keyword or phrase for this content.",
                        max_length=100,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical URL to prevent duplicate content issues.",
                    ),
                ),
                (
                    "no_index",
                    models.BooleanField(
                        default=False,
                        help_text="Prevent search engines from indexing this page.",
                    ),
                ),
                (
                    "content_abstract",
                    models.TextField(
                        blank=True,
                        help_text="A factual, concise summary of the content for AI models (max 500 characters).",
                        max_length=500,
                    ),
                ),
                (
                    "key_questions_answered",
                    models.TextField(
                        blank=True,
                        help_text="List key questions this content answers, one per line. Used for FAQ snippets and conversational AI.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("knowledge_base", "Knowledlege Base"),
                            ("well_being", "Well Being"),
                            ("Diet", "Diet"),
                        ],
                        default="knowledge_base",
                        help_text="Article category",
                        max_length=50,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Featured image displayed at the top of the article",
                        upload_to="uploads/",
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short excerpt shown in article", max_length=300
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="Full article content"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this article should be published",
                        null=True,
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("Article", "Article"),
                            ("BlogPosting", "Blog Post"),
                            ("NewsArticle", "News Article"),
                            ("Guide", "Guide"),
                        ],
                        default="Article",
                        help_text="Schema.org article type for structured data",
                        max_length=50,
                    ),
                ),
                (
                    "show_table_of_contents",
                    models.BooleanField(
                        default=True,
                        help_text="Display auto-generated table of contents",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
